---
title: "Preliminary Visualizations"
output: pdf_document
date: '2022-04-14'
---

Load Libraries
```{r}
library(ggplot2)
library(dplyr)
library(gridExtra)
```

Load Test Data
```{r}
genre <- read.csv("~/Library/Mobile Documents/com~apple~CloudDocs/SPRING2022/DATA498A/DATA498/train.csv")
summary(genre[,!names(genre) %in% c('Artist.Name', 'Track.Name')])
```

Multiple Linear Regression Predicting Popularity (if we want to do something predicting popularity)
```{r}
# get an idea of variables with predictive power
popularity_lm <- lm(Popularity~danceability+energy+key+loudness+mode+
                      speechiness+acousticness+instrumentalness+liveness+valence+tempo+
                      duration_in.min.ms+time_signature, data = genre)
summary(popularity_lm)
```

Correlation Matrix of Numeric Predictors 
```{r}
numeric_predictors <- genre[,!names(genre) %in% c('Artist.Name', 'Track.Name', 'Class', 'Mode')]
cor(numeric_predictors) 
```

```{r}
# histograms of numeric variables
par(mfrow = c(4, 4))
hist(genre$Popularity, xlab = "", main = "Popularity")
hist(genre$danceability, xlab = "", main = "Danceability")
hist(genre$energy, xlab = "", main = "Energy")
hist(genre$key, xlab = "", main = "Key")
hist(genre$loudness, xlab = "", main = "Loudness")
hist(genre$speechiness, xlab = "", main = "Speechiness")
hist(genre$acousticness, xlab = "", main = "Acousticness")
hist(genre$instrumentalness, xlab = "", main = "Instrumentalness")
hist(genre$liveness, xlab = "", main = "Liveness")
hist(genre$valence, xlab = "", main = "Valence")
hist(genre$tempo, xlab = "", main = "Tempo")
hist(genre$duration_in.min.ms, xlab = "", main = "Duration in Minutes")
hist(genre$time_signature, xlab = "", main = "Time Signature")
```


Scatterplots of highly correlated variables, colored by Genre Class, all 10 
```{r}
# valence, danceability 
val_dance <- ggplot(genre, aes(x = valence, y = danceability, color = Class)) + geom_point()

# loudness, energy
loud_energy <- ggplot(genre, aes(x = loudness, y = energy, color = Class)) + geom_point()

# loudness, acousticness 
loud_acoustic <- ggplot(genre, aes(x = loudness, y = acousticness, color = Class)) + geom_point()

# energy, acousticness 
energy_acoustic <- ggplot(genre, aes(x = energy, y = acousticness, color = Class)) + geom_point()

grid.arrange(val_dance, loud_energy, loud_acoustic, energy_acoustic, ncol = 2)

# so many classes, we need to subset and only do 2 classes at a time 
# however, we don't know what each class is -- how do we handle this?
# maybe we make visualizations and go pairwise through all of the classes ? 
```

Scatterplots, Metal vs Instrumental
```{r}

# Instrumental is 7
# Metal is 8
mi <- subset(genre, Class  == c(7, 8))
val_dance <- ggplot(mi, aes(x = valence, y = danceability, color = as.factor(Class))) + geom_point()
loud_energy <- ggplot(mi, aes(x = loudness, y = energy, color = as.factor(Class))) + geom_point()
loud_acoustic <- ggplot(mi, aes(x = loudness, y = acousticness, color = as.factor(Class))) + geom_point()
energy_acoustic <- ggplot(mi, aes(x = energy, y = acousticness, color = as.factor(Class))) + geom_point()
grid.arrange(val_dance, loud_energy, loud_acoustic, energy_acoustic, ncol = 2) 
```

Country vs Hip Hop
```{r}
# Country is 4
# Hip Hop is 5
chh <- subset(genre, Class  == c(4, 5))
val_dance <- ggplot(chh, aes(x = valence, y = danceability, color = as.factor(Class))) + geom_point()
loud_energy <- ggplot(chh, aes(x = loudness, y = energy, color = as.factor(Class))) + geom_point()
loud_acoustic <- ggplot(chh, aes(x = loudness, y = acousticness, color = as.factor(Class))) + geom_point()
energy_acoustic <- ggplot(chh, aes(x = energy, y = acousticness, color = as.factor(Class))) + geom_point()
grid.arrange(val_dance, loud_energy, loud_acoustic, energy_acoustic, ncol = 2) 
```

